name: DEV - Build & Deploy

on:
  push:
    branches: ["develop"]
jobs:
  build-and-deploy-fullstack-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Git
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build Full Stack App
        run: |
          yarn install && yarn bootstrap
          yarn build --scope=frontend
          echo "Copying static content..."
          cp -r src/frontend/packages/app/dist/ src/backend/client/
          yarn build --scope=backend
        shell: bash
