name: DEV - Build & Deploy

on:
  push:
    branches: ["develop"]
jobs:
  build-deploy-fullstack-app:
    runs-on: ubuntu-latest
    steps:
      - name: Git
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Build Full Stack App
        run: |
          yarn install && yarn bootstrap
          yarn build --scope=frontend
          cp -r src/frontend/packages/app/dist/ src/backend/client/
          yarn build --scope=backend
        shell: bash
